### ISSUE TITLE
Add a feature to return ticket summary

### ISSUE THREAD

**Issue by dmranck** [dmranck/ticketutil#12]
Add a feature that returns info on a ticket - something like a get_ticket_info() method.

**Comment by dmranck** [comment]
ServiceNow already has a get_ticket_content() method. Add something like this to the other tools.
https://github.com/dmranck/ticketutil/blob/master/ticketutil/servicenow.py#L66

**Comment by dmranck** [comment]
This is fairly high priority as it would complete the 'R' in CRUD (Create, Read, Update, Delete).

**Comment by mjagelka** [comment]
All tools contain get_ticket_content() method now together with ticket_content attribute.

**Comment by dmranck** [comment]
Awesome, @mjagelka! Thanks for all your work on this!
