### ISSUE TITLE
get_ticket_content return

### ISSUE THREAD

**Issue by pzubaty** [dmranck/ticketutil#36]
@dmranck 
https://github.com/dmranck/ticketutil/blob/4e713050ab71b1f2531daf630a6c74977f19e13b/ticketutil/servicenow.py#L95 I know that every method should return a named tuple, but in this case it doesn't look very nice.

**Comment by dmranck** [comment]
Hey @pzubaty , what do you mean it doesn't look very nice? The code itself, or the way the user will access the ticket content?

There's a Note in the docs on how the user can access the content with simply (t.ticket_content). I didn't think this was messy.

http://ticketutil.readthedocs.io/en/latest/Usage.html#return-statements

**Comment by pzubaty** [comment]
I mean the code on the "return" line, it looks rather wild. :)

**Comment by dmranck** [comment]
I don't think it's bad! Another solution would be to put the ['result'][0] stuff on line 94 instead, but it's kind of similar. If you'd like to fix it, feel free and I can merge it in. :)
