### ISSUE TITLE
JiraTicket: UnboundLocalError when using an invalid hostname

### ISSUE THREAD

**Issue by mherbert25** [dmranck/ticketutil#5]
I purposely mis-typed the jira hostname and tried to connect. It threw an UnboundLocalError. Here is the traceback:

> INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): fake-jira.fake.com
> ERROR:root:Error authenticating to http://fake-jira.fake.com/step-auth-gss. No valid kerberos principal found.
> ERROR:root:HTTPConnectionPool(host='fake-jira.fake.com', port=80): Max retries exceeded with url: /step-auth-gss (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f64a15f4b90>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
> INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (2): fake-jira.fake.com
> Traceback (most recent call last):
>   File "utils.py", line 16, in <module>
>     create_jira('DEVOPSA', 'test summary', 'test description')
>   File "utils.py", line 12, in create_jira
>     priority = priority,
>   File "/usr/lib/python2.7/site-packages/ticketutil/jira.py", line 75, in create
>     self._create_ticket_request(params)
>   File "/usr/lib/python2.7/site-packages/ticketutil/jira.py", line 134, in _create_ticket_request
>     logging.error("Error creating ticket - {0}".format(list(r.json()['errors'].values())[0]))
> UnboundLocalError: local variable 'r' referenced before assignment

**Comment by dmranck** [comment]
Thanks @mherbert25 , I'll plan to fix this this week.

**Comment by dmranck** [comment]
To reproduce:

`from ticketutil.jira import JiraTicket
t = JiraTicket('http://fake-jira.fake.com', 'PROJECT')
t.create(summary='summary', description='description')`

**Comment by dmranck** [comment]
Will work on this along with adding better error handling across the whole ticketutil.

**Comment by dmranck** [comment]
I created a TicketException class and I raise it in the situation referenced in this issue. If you can't create the Ticket object because of a failing request to the URL, an exception should be raised, because all other Ticket methods won't work.

https://github.com/dmranck/ticketutil/commit/0403e7e5c4013e5400c31d1389a5fa6d45da4281
