### ISSUE TITLE
Cannot initialize a JiraTicket object if the Jira URL has a trailing slash

### ISSUE THREAD

**Issue by ddelabru** [dmranck/ticketutil#67]
If the provided Jira URL has a trailing slash, initializing a `JiraTicket` object results in an incorrectly formed API URL, and ultimately leads to a `JSONDecodeError`. The resulting traceback does not indicate that the trailing slash could be the problem. The workaround for this behavior is easy (omit the trailing slash), but pinpointing the cause of the traceback can be difficult.

**Comment by dmranck** [comment]
Thanks for opening this issue, @ddelabru ! Would you be interested in fixing the code to handle a Jira URL with or without a trailing slash, and then submitting a PR?

**Comment by ddelabru** [comment]
@dmranck I would, but first I'd like to ask if it's alright to add a dependency on `six`. I think the best-practice way to do this would be to use `urllib.parse` from the Python standard library, but this is `urlparse` in older Pythons.

**Comment by ddelabru** [comment]
Ah, never mind; it looks like six is already an indirect dependency.

**Comment by dmranck** [comment]
@ddelabru Let me know if you'd like to see this fix on PyPI in a new ticketutil release, and I can add that to my to-do list.

**Comment by ddelabru** [comment]
@dmranck, I'm in no rush; once I figured out what was causing my issue with ticketutil it was easy enough to work around.

**Comment by dmranck** [comment]
Ok, sounds good - thanks. Closing out this issue now.
