### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by dmranck** [dmranck/ticketutil#9]
Write unit tests.

**Comment by dmranck** [comment]
This should be done for all 5 tools in a consistent manner. Unit tests already exist for ServiceNowTicket.

**Comment by mjagelka** [comment]
Unit tests for ticket.py were successfully added.

**Comment by mjagelka** [comment]
Unit tests for jira, bugzilla, redmine and rt were successfully added.

**Comment by dmranck** [comment]
Thanks, @mjagelka !
